### ISSUE TITLE
Option to turn of the auto deactivation

### ISSUE THREAD

**Issue by TomTheDragon** [EionRobb/skype4pidgin#364] opened 2015-12-01 18:33 UTC
Could we have an option to turn of the auto deactivation, after a connection error?
This really can be a problem when your internet connection is not that stable or you want to run a connection for many days on a ADSL connection, where it automatically disconnects your connection every day.

**Comment by EionRobb** [comment] 2015-12-09 02:39
Unfortunately it's difficult to know whether an auth failure has occurred because of a bad password or because of network failure.

Are you able to send through a debug log, it might be possible to detect the network failure if we know what to look for.

**Comment by Dagger3340** [comment] 2015-12-30 19:01
I'm possibly hitting the same issue with SkypeWeb. In my case, every time I come out of standby, Pidgin reports "Failed getting MSPRequ cookie" and I have to manually tell it to reconnect. (I'm using WiFi; maybe it'd be harder to reproduce on Ethernet, but for me this happens on every single standby/resume cycle.)

Here's the debug log:

```
(12:19:47) network: found network '<domain>'
(12:19:47) network: Received Network Change Notification. Current network count is 1, previous count was 1.
(12:19:47) autorecon: do_signon called
(12:19:47) autorecon: calling purple_account_connect
(12:19:47) account: Connecting to account <user>@outlook.com.
(12:19:47) connection: Connecting. gc = 05627BA8
(12:19:47) util: requesting to fetch a URL
(12:19:47) dnsquery: Performing DNS lookup for login.skype.com
(12:19:47) autorecon: done calling purple_account_connect
(12:19:56) dnsquery: IP resolved for login.skype.com
(12:19:56) proxy: Attempting connection to 91.190.218.34
(12:19:56) proxy: Connecting to login.skype.com:443 with no proxy
(12:19:56) proxy: Connection in progress
(12:19:56) proxy: Connecting to login.skype.com:443.
(12:19:56) proxy: Error connecting to login.skype.com:443 (Windows socket error #10065).
(12:19:56) proxy: Connection attempt failed: Windows socket error #10065
(12:19:56) g_log: skypeweb_string_get_chunk: assertion `haystack && start && end' failed
(12:19:56) connection: Connection error on 05627BA8 (reason: 2 description: Failed getting MSPRequ cookie)
(12:19:56) account: Disconnecting account <user>@outlook.com (0554EEE8)
(12:19:56) connection: Disconnecting connection 05627BA8
(12:19:56) GLib: g_source_remove: assertion `tag > 0' failed
(12:19:56) GLib: g_source_remove: assertion `tag > 0' failed
(12:19:56) GLib: g_source_remove: assertion `tag > 0' failed
(12:19:56) skypeweb: getting url /logout
(12:19:56) skypeweb: sending headers:
GET /logout HTTP/1.0
Host: login.skype.com
Connection: close
Accept: */*
Cookie: 
Accept-Encoding: gzip
Accept-Language: en-GB, en, C


(12:19:56) dnsquery: Performing DNS lookup for login.skype.com
(12:19:56) skypeweb: destroying 0 waiting connections
(12:19:56) skypeweb: destroying 1 incomplete connections
(12:19:56) connection: Destroying connection 05627BA8
```

**Comment by felagund** [comment] 2016-09-18 13:28
A solution would be to try to reconnect right after a failure, after a 10 second delay, after a minute delay and after 3 minute delay and only then give up or something like that.

For me, when I start my computer, pidgin starts before my wifi connection is up and so the plugin gets turned off and I have to manually re-enable it. It seems to happen on almost every boot.

**Comment by felagund** [comment] 2016-09-20 08:45
Hm, upon investigation, Facebook and Hangouts plugin do what I propose-  they connect after about 40 seconds or so, sometimes even earlier. Only Skype is an outlier that never connects once it is disconnected upon startup.

**Comment by EionRobb** [comment] 2017-03-27 05:00
Should have been fixed by https://github.com/EionRobb/skype4pidgin/commit/92c376f57934b7af4564332e0a1f7a75e0473b4e

**Closed by EionRobb** 2017-03-27 05:00 UTC
