### ISSUE TITLE
suddenly stopped connecting

### ISSUE THREAD

**Issue by veritas1980** [EionRobb/skype4pidgin#396] opened 2016-01-20 19:59 UTC
about 15 minutes ago, I started having problems, the skype account in pidgin wont connect, just the reconnect option over and over. I only downloaded the plugin perhaps a week ago. "failed getting registration token"

**Comment by psychonic** [comment] 2016-01-20 20:37
I am having the same issue starting from around that time. It may just be a temporary server-side issue.

**Comment by zetaPRIME** [comment] 2016-01-20 21:14
same here; skypeweb itself works, suspecting they changed something

**Comment by baskervald** [comment] 2016-01-20 21:23
I can't connect on the actual site either, so I assume it's an issue with SkypeWeb itself

**Comment by nelsonw2014** [comment] 2016-01-20 21:25
Glad there's already an issue up :) Same issue

**Comment by cbenard** [comment] 2016-01-20 23:08
I can't connect either. I sent Rob a log earlier today and commented on #376 since that's the message I'm getting.

**Comment by GammaPaladin** [comment] 2016-01-21 01:26
Yeah, I can't connect either, ended up missing an important appointment. The skypeweb web page works for me, but pidgin does not.

I too suspect MS changed something. Possibly deliberately to break third party plugins like this, because they're a bunch of dicks.

**Comment by nelsonw2014** [comment] 2016-01-21 04:14
The problem is resolved, whatever it is

**Comment by veritas1980** [comment] 2016-01-21 09:56
Yeah, its working again.

**Comment by cbenard** [comment] 2016-01-21 14:11
Mine is working as well.

**Comment by psychonic** [comment] 2016-01-21 15:45
It's working again for me today as well.

**Comment by cbenard** [comment] 2016-01-22 17:23
Back to not working. Same error.

**Comment by Rydian** [comment] 2016-01-22 17:51
I've been getting it on and off for a while, and yeah it just hit again.

**Comment by doctorcolossus** [comment] 2016-01-22 18:07
Same here. `Failed getting Registration Token`
I can log in fine through the web interface.

**Comment by EionRobb** [comment] 2016-01-22 20:17
Sorry all for the mess with the unstable connections. I'm definitely aware of the problem. :) The plan is to try a few different servers if the main one fails. 

Just hang in there for now and hope that MS get things boring a little better and I'll keep trying to work out how I'm going to get this to work

Apologies to all, again.

**Comment by cbenard** [comment] 2016-01-22 20:59
@EionRobb thank you for working on this so hard! It's much appreciated!

**Comment by veritas1980** [comment] 2016-01-23 19:53
Same error today again.

**Comment by Ghabry** [comment] 2016-01-25 11:33
The website doesn't work in Firefox when they have server issues but in Chrome. oO

**Comment by veritas1980** [comment] 2016-01-25 15:52
and its going on again today.

**Comment by ojdo** [comment] 2016-01-25 15:54
Yep, same here (Europe). This issue tracker seems to become a more sensitive version of the [Skype heartbeat](http://heartbeat.skype.com/), which doesn't (yet) announce any problems. That, or they are changing something behind the scenes...

**Comment by cbenard** [comment] 2016-01-25 15:55
@ojdo, funny! I'm having issues right now too.

**Comment by xvitaly** [comment] 2016-01-25 15:59
@ojdo https://web.skype.com/ not working today.

**Comment by wendall911** [comment] 2016-01-26 18:30
I haven't been able to connect since it went down on the 21st. Was sporadic last week, now it fails every time the last two days. Heartbeat shows the issue as resolved, but doesn't appear to be. Or the fix they used broke it for the plugin, not sure.

**Comment by wendall911** [comment] 2016-01-27 18:22
I was able to connect today for the first time. It looks like they are still having some issues even though it shows resolved. No action needed here, just an update.

**Comment by muchtall** [comment] 2016-01-29 15:18
Responses from client-s.gateway.messenger.live.com have been taking rather long. I'm seeing that many of them in the browser take 30s+ to complete, and many simply time out. It appears that the skypeweb plugin times out and then gives up reconnecting (throwing up the "Failed getting Registration Token" message)  whereas the browser-based client retries immediately, and keeps retrying until it succeeds. @EionRobb, could the plugin behavior be changed to retry as well? If one is patient enough to keep hitting "Re-enable" after each timeout, it eventually seems to connect and stay connected.

And thanks for this plugin! I hate Skype for a number of reasons, the greatest of which is the horrible client. This plugin in combo with Pidgin finally makes chat in Skype bearable.

**Comment by veritas1980** [comment] 2016-01-29 19:17
It does indeed make it bearable. However, Since it relies on skype for web, which continually has problems, that's its one downfall.

**Comment by cypa** [comment] 2016-02-01 18:27
`Failed getting Skype Token` as long as few hours ...

**Comment by xvitaly** [comment] 2016-02-03 13:08
SkypeWeb is down today.

**Comment by GammaPaladin** [comment] 2016-02-04 18:57
This is incredibly frustrating... Every day I can't get the plugin to connect until it's too late to make the chat I'm supposed to be in at 1pm. Any progress on this fix?

**Comment by xvitaly** [comment] 2016-02-04 19:01
> Any progress on this fix?

Ask Microsoft about this. Microsoft SkypeWeb is too unstable for the last two weeks. :-)

**Comment by doctorcolossus** [comment] 2016-02-04 19:21
The best clue so far was posted ten days ago by Ghabry:
> The website doesn't work in Firefox when they have server issues but in Chrome. oO

I can confirm that this is true. If you really need to use Skype, try with Chromium or perhaps another Webkit-based browser.

Someone more motivated than I could probably use this clue to come up with a fix for the libpurple plugin. You would probably beat Microsoft to it...

Another option would be to open a Mozilla bug (if there isn't already one), see if someone in the Mozilla team is able to identify the problem, and then adapt it to the libpurple plugin if possible.

A longer-term solution is to educate your contacts about alternatives. I have been using the Blink SIP client with great success for audio calls. With a few of my contacts it works with video too. There are also quite a few sites for making WebRTC audio/video calls in your browser, and if none of those work for you, there is Google Hangouts. And I shouldn't have to tell Pidgin users about all of the available IM alternatives... Thanks in advance to anyone who spreads the good word about Skype alternatives.

**Comment by GammaPaladin** [comment] 2016-02-04 19:39
Actually it works fine in firefox for me, even when the skypeweb plugin is refusing to connect (Like it is right now, and pretty much every day before about 4PM)

**Comment by doctorcolossus** [comment] 2016-02-04 19:49
Same here actually, but not consistently... I can usually connect in Firefox, but sometimes it takes a while after opening the page before I reach an 'online' state, can see contacts' availability, and can send & receive messages. And sometimes when attempting to send a message in Firefox, it will hang and say 'Sending...' for a long-ass time. Then it finally shows 'Sent' or 'Failed'. I don't experience such issues in Chromium.

**Comment by dequis** [comment] 2016-10-03 01:49
Considering the lack of comments in the last few months, and how most of them seem to suggest this was an intermittent server issue, closing this.

**Closed by dequis** 2016-10-03 01:49 UTC
