### ISSUE TITLE
Skype TFA does not work. Error = "Failed getting Magic T value"

### ISSUE THREAD

**Issue by RBLevin** [EionRobb/skype4pidgin#564] opened 2017-08-31 13:46 UTC
Installed latest rev. Used my Microsoft ID and PW. That didn't work. Then I tried an app-specific password. That didn't work. Then I followed the troubleshooting flowchart.  That didn't work, and also revealed that the "alt login" feature recommended for TFA does not exist or is not documented correctly in the plugin. There is a blank checkbox on the Advanced tab, which I tried, to no avail.

**Comment by dequis** [comment] 2017-08-31 14:09
The flowchart says "Can you build the latest git version?"

Did you build the latest git version?

**Comment by RBLevin** [comment] 2017-08-31 14:29
No, I haven't compiled anything in years. :-0

I did report the bug in github.

**Comment by dequis** [comment] 2017-08-31 16:10
Wait for the next release then.

Duplicate of #385

**Closed by dequis** 2017-08-31 16:10 UTC

**Comment by RBLevin** [comment] 2017-08-31 18:20
Thanks. Will do.
