### ISSUE TITLE
Failed getting Registration Token

### ISSUE THREAD

**Issue by dignityinside** [EionRobb/skype4pidgin#395] opened 2016-01-18 14:50 UTC
Disconnection with error "Failed getting Registration Token".

**Comment by TETYYS** [comment] 2016-01-18 15:05
https://github.com/EionRobb/skype4pidgin/issues/376

**Comment by EionRobb** [comment] 2016-01-19 04:04
Yep, duplicate of #376 although might have been just a one off server down?

**Closed by EionRobb** 2016-01-19 04:04 UTC
