### ISSUE TITLE
Sending files and embedding images is not working on version 1.4

### ISSUE THREAD

**Issue by alex3kov** [EionRobb/skype4pidgin#575] opened 2017-11-12 09:27 UTC
1) In Pidgin's chat window button Insert -> Image is inactive:
![f](https://user-images.githubusercontent.com/3616242/32697583-a90180ca-c7a4-11e7-8ad0-72e01ec1c82f.png)

2) Sending files reports progress and "successful" message, but on the other end user doesn't receive anything (no notification of any kind). Sender: Pidgin 2.12.0, purple-skypeweb 1.4, recipient: official windows Skype client 7.40.66.104.
In Pidgin:
```
(12:15:02) Offering to send Troll_seal_of_approval.jpg to a_fake_skype
(12:15:02) Transfer of file Troll_seal_of_approval.jpg complete
```
In recipient Skype client: nothing.

**Comment by f03el** [comment] 2017-11-13 08:39
Seems like a duplicate of #423.

**Comment by dequis** [comment] 2017-11-19 15:23
Duplicate of #423

**Closed by dequis** 2017-11-19 15:23 UTC
