### ISSUE TITLE
Pidgin displays phantom skype contact

### ISSUE THREAD

**Issue by zevelorgani** [EionRobb/skype4pidgin#442] opened 2016-06-19 19:41 UTC
When I connect to Skype, Pidgin shows a contact that looks like cid-(xxxxxxxxxxxxxxxxxxx)@outlook.com where each 'x' is a decimal digit.  This contact is not shown in the desktop skype application.

When I look at the log for that contact, I see that it echoes every message that I send to it, leading me to believe that is represents my own account.

Why is it shown and how can I prevent it?

**Comment by reinforce** [comment] 2016-06-19 19:42
Duplicate of #432

**Closed** 2016-06-20 03:10 UTC
