### ISSUE TITLE
Message that contains copypasted received message appears with very small font when received on skype

### ISSUE THREAD

**Issue by Barteks2x** [EionRobb/skype4pidgin#524] opened 2017-02-17 22:15 UTC
When I receive and send something like this:
![image_pidgin](https://cloud.githubusercontent.com/assets/1349112/23085240/e2e73a5c-f566-11e6-91b7-4f6a3245c110.png)
Then on skype on windows the second message is received like this:
![image_skype](https://cloud.githubusercontent.com/assets/1349112/23085251/eedab06e-f566-11e6-8a45-513b94a9c176.png)

**Comment by dequis** [comment] 2017-02-18 01:28
Duplicate of #515

**Closed by dequis** 2017-02-18 01:28 UTC
