### ISSUE TITLE
Failed getting Skype Token

### ISSUE THREAD

**Issue by HaltarDhrim** [EionRobb/skype4pidgin#489] opened 2016-10-19 08:08 UTC
Hi, sometimes I have a problem with Pidgin when trying to login into my Skype account.
The error message says "Failed getting Skype Token".
Usually I fix it by doing the login in Skype, then quit it and retry to connect with Pidgin, and it works.
This time it's not working though... Any advice?
Thank you all!

**Comment by poisonby** [comment] 2016-10-19 08:55
I have the same problem.

**Comment by EionRobb** [comment] 2016-10-19 09:07
Duplicate of issue #479

Try updating to 1.2.2 of the plugin :)

**Closed by EionRobb** 2016-10-19 09:07 UTC

**Comment by poisonby** [comment] 2016-10-19 19:20
Updated to 1.2.2 (that update wasn't available when I posted here), that got rid of the token error but now I get this:

> skypeweb - Login error: Failed getting Magic T value

Is this related? I've never had any errors before this.

**Comment by xion87** [comment] 2016-11-04 16:15
Same error
