### ISSUE TITLE
when someone adds me as a contact, it asks every time I connect to authorize them

### ISSUE THREAD

**Issue by ptx0** [EionRobb/skype4pidgin#583] opened 2017-12-31 21:02 UTC
When someone added me lately, I clicked authorize in Pidgin but it kept asking to authorize on every reconnect.

I logged into skypweb and could not see any awaiting authorizations so I manually added the user to my contacts. I tried reconnecting after, and it still asks.

I compiled latest master and this issue persists.

**Comment by dequis** [comment] 2018-01-01 00:58
Duplicate of #577

**Closed by dequis** 2018-01-01 00:58 UTC
